### ISSUE TITLE
Align Server Deployment 

### ISSUE THREAD

**Issue by ChristopherPHolder** [ChristopherPHolder/app-speed#50]
## TODOS

- [x] Server Should be deployed with NX Command as target
- [x] NX command should allow specifying dev or prod
- [x] Deployment Target Should be part of the same pipeline sequence and have dependencies
- [x] Deployment Should utilize NX affected
