### ISSUE TITLE
Improve Yargs Command Typing

### ISSUE THREAD

**Issue by ChristopherPHolder** [ChristopherPHolder/app-speed#79]
## Description

Main currently looks like this:

```ts
const argv = await yargs(hideBin(process.argv))
  .options({ verbose, help, shutdown, dryRun })
  .command([ userFlowCommand ])
  .parse();
```

This means that all the commands have a default set of options. 

However, the command typing is incorrect:

```ts
type UserFlowCommand = CommandModule<NonNullable<unknown>, UserFlowCommandOptions>
```

As it should include the global types in the command generict type.

---

We are also incorrectly declarring the command modules in yargs as we pass it as a command array and it propably should not be, eg: `.command([ userFlowCommand ])`.

---

We are also incorrectly using the Command builder 

```ts
const userFlowBuilder: CommandBuilder = { queue, store };
```

This should be using the proper `(argv) => argv.options(...options)` with its correct typing.

---

We are also incorrectly using the type declarations of the command arguments. We should use the yargs typing that inferres it insead of creating out own interface!

## TODOS

- [ ] Fix command module typing to include generics of options
- [ ] Fix command declaration to not be array of commands
- [ ] Use typed functional command builders
- [ ] Use InferredOptionTypes instead of our own interface
